[project]
name = "goones"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
    "requests>=2.32.5",
]
